services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - dashboard
      - api
    restart: unless-stopped
    networks:
      - dengue_net

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    restart: unless-stopped
    networks:
      - dengue_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    networks:
      - dengue_net

networks:
  dengue_net:
    driver: bridge
